// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvawttgzuirjmpdnmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dmF3dHRnenVpcmptcGRubWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNDY2NzIsImV4cCI6MjA4MzgyMjY3Mn0.WKT-4sKISsWGJUo3_t4H6yZ1FcXLpzSrkaaxnUJxOhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});